org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

# Fabric Mappings and versions
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.2
loader_version=0.19.2

# Mod Information
mod_id=journeymode
mod_name=Journey Mode
mod_version=1.7.1
mod_group=com.aryangpt007.journeymode
mod_authors=Aryangpt007
mod_description=Unlock unlimited access to items after collecting enough of them
mod_license=MIT

# Dependency versions
fabric_version=0.102.1+1.21.1
