#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# NOTE: This is a standard wrapper launcher script. The wrapper JAR/properties
# in ./gradle/wrapper control the Gradle version (already set to 8.10.2).

APP_HOME=$(cd "$(dirname "$0")" && pwd)

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
  echo "ERROR: Gradle wrapper JAR not found: $CLASSPATH" >&2
  exit 1
fi

# Use JAVA_HOME if set, otherwise fall back to whatever is on PATH.
if [ -n "$JAVA_HOME" ] ; then
  JAVA_EXEC="$JAVA_HOME/bin/java"
else
  JAVA_EXEC="java"
fi

exec "$JAVA_EXEC" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
