org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

# RetroFuturaGradle targets Java 8 for Minecraft 1.12.2 compilation
org.gradle.java.home=C:/Program Files/Java/jdk-17.0.4.1

minecraft_version=1.12.2
forge_version=14.23.5.2860

mod_id=journeymode
mod_name=Journey Mode
mod_version=1.7.1
mod_group_id=com.aryangpt007.journeymode
mod_authors=Aryangpt007
mod_description=Unlock unlimited access to items after collecting enough of them
